name: deploy-demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello build!"
  
  deploy-test:
    runs-on: ubuntu-latest

    needs: build
    environment: 
      name: test
      url: https://docs.github.com
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello test deploy!"
  
  deploy-production:
    runs-on: ubuntu-latest

    needs: build
    environment: 
      name: production
      url: https://docs.github.com
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello production deploy!"
